In [1]:
import pandas as pd

# Login using e.g. `huggingface-cli login` to access this dataset
df = pd.read_csv("hf://datasets/mramazan/One-Piece-Transcripts-with-Character-Names-382-777/onepiece.csv")

/Users/deren/Documents/projects/RAGs/rag-from-zero-to-hero/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100259 entries, 0 to 100258
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   episode    100259 non-null  int64
 1   start      100259 non-null  str
 2   end        100259 non-null  str
 3   character  100259 non-null  str
 4   text       100259 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [3]:
df.head()

,episode,start,end,character,text
0,384,0:02:31.76,0:02:32.73,Narrator,Wealth.
1,384,0:02:32.73,0:02:33.99,Narrator,Fame.
2,384,0:02:33.99,0:02:34.79,Narrator,Power.
3,384,0:02:36.01,0:02:38.75,Narrator,"The man who once owned everything,"
4,384,0:02:38.75,0:02:39.92,Narrator,"The Pirate King,"

In [4]:
len(df)

100259

In [5]:
df[["episode", "character", "text"]].head()

   episode character                                text
0      384  Narrator                             Wealth.
1      384  Narrator                               Fame.
2      384  Narrator                              Power.
3      384  Narrator  The man who once owned everything,
4      384  Narrator                    The Pirate King,

In [7]:
len(df["episode"].unique())

391

In [21]:
print(df["text"][11])

Find it!

In [9]:
len(df["text"][11])

8